/**
 * Cleaning pass (plan §4.2) — DOM/tree side.
 *
 *  - strip platform cruft attributes (wp-*, tracking data-attrs, framework junk)
 *  - move captured inline-SVG markup onto `raw`
 *  - detect repeated sibling patterns and flag them likelyDynamic (CMS loops)
 *  - rename auto-generated class names (css-1x2y3z, sc-*, jsx-*) to rp-block-N
 *  - classify captured scripts (framework / tracking / custom)
 */

import type {
  ExtractionResult,
  IRNode,
  RawCapture,
  RawCapturedScript,
  ScriptInfo,
} from '../types.js';
import { cleanCss, type CssUsage } from './css.js';

/* ---------- attribute cruft ---------- */

const CRUFT_ATTR_PATTERNS: RegExp[] = [
  /^data-wp-/,
  /^data-elementor/,
  /^data-shopify/,
  /^data-widget_type$/,
  /^data-gtm/,
  /^data-ga-?/,
  /^data-track/,
  /^data-analytics/,
  /^data-hs-/,
  /^data-hubspot/,
  /^data-v-[a-f0-9]+$/, // Vue scoped
  /^data-reactid$/,
  /^data-react-/,
  /^data-emotion/,
  /^data-styled/,
  /^data-astro-/,
  /^data-framer-/,
  /^data-testid$/,
  /^data-cy$/,
  /^data-qa$/,
  /^ping$/,
];

/* ---------- auto-generated class detection ---------- */

const AUTOGEN_CLASS_PATTERNS: RegExp[] = [
  /^css-[a-z0-9]{4,}$/i, // emotion
  /^sc-[a-zA-Z0-9_-]{4,}$/, // styled-components
  /^jsx-\d+$/, // styled-jsx
  /^[a-zA-Z][a-zA-Z0-9]*_[a-zA-Z][a-zA-Z0-9-]*__[a-zA-Z0-9_-]{5,}$/, // hashed CSS modules
  /^[a-z]+-module--[a-zA-Z0-9-]+--[a-z0-9]{5,}$/i, // gatsby css modules
];

export function isAutoGeneratedClass(name: string): boolean {
  return AUTOGEN_CLASS_PATTERNS.some((re) => re.test(name));
}

/* ---------- script classification ---------- */

const TRACKING_RE =
  /googletagmanager|google-analytics|gtag\(|gtag\.|fbevents|fbq\(|connect\.facebook|hotjar|clarity\.ms|clarity\(|segment\.(io|com)|mixpanel|amplitude|doubleclick|adsbygoogle|googlesyndication|cookiebot|onetrust|usercentrics|intercom|crisp\.chat|tawk\.to|hs-scripts|hubspot|tiktok|snap\.licdn|pixel|matomo|plausible\.io|umami|dataLayer/i;

const FRAMEWORK_RE =
  /jquery|react(-dom)?[.-]|vue(\.runtime)?[.-]|angular|webpack|__NEXT_DATA__|_next\/static|nuxt|polyfill|core-js|bootstrap(\.bundle)?[.-]|swiper|slick|gsap|lodash|moment(\.min)?\.js|wp-includes|wp-content\/(plugins|themes)|wp-emoji|cdn\.jsdelivr|cdnjs\.cloudflare|unpkg\.com|googleapis\.com/i;

export function classifyScripts(raw: RawCapturedScript[]): ScriptInfo[] {
  const out: ScriptInfo[] = [];
  for (const s of raw) {
    if (s.src) {
      const classification = TRACKING_RE.test(s.src)
        ? 'tracking'
        : FRAMEWORK_RE.test(s.src)
          ? 'framework'
          : 'custom';
      out.push({ kind: 'external', src: s.src, classification });
    } else if (s.content) {
      const classification = TRACKING_RE.test(s.content)
        ? 'tracking'
        : FRAMEWORK_RE.test(s.content)
          ? 'framework'
          : 'custom';
      out.push({ kind: 'inline', content: s.content, classification });
    }
  }
  return out;
}

/* ---------- tree cleaning ---------- */

function cleanNode(node: IRNode): IRNode | null {
  if (node.type === 'text') return node;

  const attrs = { ...(node.attrs ?? {}) };

  // inline SVG passthrough captured by the extractor
  if (node.tag === 'svg' && attrs['data-repage-svg']) {
    const raw = attrs['data-repage-svg'];
    delete attrs['data-repage-svg'];
    return { type: 'element', tag: 'svg', raw, attrs: {}, classes: [], children: [] };
  }

  for (const key of Object.keys(attrs)) {
    if (CRUFT_ATTR_PATTERNS.some((re) => re.test(key))) delete attrs[key];
  }

  const children: IRNode[] = [];
  for (const child of node.children ?? []) {
    const cleaned = cleanNode(child);
    if (cleaned) children.push(cleaned);
  }

  // drop empty leftovers that carry nothing (common after cruft removal)
  const isStructural = node.tag && ['div', 'span'].includes(node.tag);
  if (
    isStructural &&
    children.length === 0 &&
    (node.classes ?? []).length === 0 &&
    Object.keys(attrs).length === 0
  ) {
    return null;
  }

  return { ...node, attrs, children };
}

/* ---------- dynamic region detection ---------- */

function signature(node: IRNode): string | null {
  if (node.type !== 'element') return null;
  const cls = (node.classes ?? []).slice(0, 2).join('.');
  return `${node.tag}.${cls}`;
}

function detectDynamicRegions(node: IRNode): void {
  const children = node.children ?? [];
  let i = 0;
  while (i < children.length) {
    const sig = signature(children[i]);
    if (!sig || sig.endsWith('.')) {
      // unclassed elements repeat trivially (p, li without classes still count)
      const bareSig = children[i].type === 'element' ? children[i].tag : null;
      if (!bareSig || !['li', 'article'].includes(bareSig)) {
        i++;
        continue;
      }
    }
    let j = i + 1;
    while (j < children.length && signature(children[j]) === sig) j++;
    const size = j - i;
    if (size >= 3 && children[i].type === 'element' && (children[i].children ?? []).length > 0) {
      for (let k = i; k < j; k++) {
        children[k].meta = { ...children[k].meta, likelyDynamic: true };
      }
      children[i].meta = {
        ...children[i].meta,
        dynamicGroupStart: true,
        dynamicGroupSize: size,
      };
    }
    i = j;
  }
  for (const child of children) detectDynamicRegions(child);
}

/* ---------- usage collection + class renaming ---------- */

function collectUsage(node: IRNode, usage: CssUsage): void {
  if (node.type === 'element') {
    if (node.tag) usage.tags.add(node.tag);
    for (const c of node.classes ?? []) usage.classes.add(c);
    const id = node.attrs?.id;
    if (id) usage.ids.add(id);
  }
  for (const c of node.children ?? []) collectUsage(c, usage);
}

function buildRenameMap(usage: CssUsage): Record<string, string> {
  const map: Record<string, string> = {};
  let counter = 1;
  for (const cls of usage.classes) {
    if (isAutoGeneratedClass(cls)) {
      map[cls] = `rp-block-${counter++}`;
    }
  }
  return map;
}

function applyRenames(node: IRNode, map: Record<string, string>): void {
  if (node.type === 'element' && node.classes) {
    node.classes = node.classes.map((c) => map[c] ?? c);
  }
  for (const c of node.children ?? []) applyRenames(c, map);
}

/* ---------- main entry ---------- */

export function runCleaningPass(url: string, capture: RawCapture): ExtractionResult {
  const warnings = [...capture.warnings];
  if (!capture.tree) {
    throw new Error('Page produced no <body> content to extract.');
  }

  const cleanedTree = cleanNode(capture.tree) ?? {
    type: 'element' as const,
    tag: 'body',
    attrs: {},
    classes: [],
    children: [],
  };

  // body itself becomes a plain container in the output
  if (cleanedTree.tag === 'body') cleanedTree.tag = 'div';

  detectDynamicRegions(cleanedTree);

  const usage: CssUsage = { classes: new Set(), ids: new Set(), tags: new Set() };
  collectUsage(cleanedTree, usage);

  const renameMap = buildRenameMap(usage);
  applyRenames(cleanedTree, renameMap);
  for (const [from, to] of Object.entries(renameMap)) {
    usage.classes.delete(from);
    usage.classes.add(to);
  }
  if (Object.keys(renameMap).length > 0) {
    warnings.push(
      `Renamed ${Object.keys(renameMap).length} auto-generated class name(s) to rp-block-N.`,
    );
  }

  const { css, fonts } = cleanCss(capture.css, usage, renameMap);
  const scripts = classifyScripts(capture.scripts);

  let origin = '';
  try {
    origin = new URL(url).origin;
  } catch {
    /* validated upstream */
  }

  return {
    url,
    origin,
    title: capture.title || 'Untitled page',
    extractedAt: new Date().toISOString(),
    ir: cleanedTree,
    css,
    scripts,
    fonts,
    warnings,
    renamedClasses: renameMap,
  };
}
